iDezBookWeb/src/main/java/com/davlopes/bookstore/CategoriaBean.java
package main.java.com.davlopes.bookstore;

import java.io.Serializable;
import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.davlopes.bookstore.manager.GerenciadorDeCategorias;
import com.davlopes.bookstore.models.Categoria;

@Named
@ConversationScoped
public class CategoriaBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private Conversation conversation;

	private Categoria categoria;

	@EJB
	private GerenciadorDeCategorias gerenciador;

	private List<Categoria> categorias;

	public CategoriaBean() {
		this.categoria = new Categoria();
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public String cadastrar() {
		this.gerenciador.cadastrar(this.categoria);

		return "cat_admin_listar.xhtml";
	}

	public String remover(Categoria c) {
		this.gerenciador.remover(c);

		return "cat_admin_listar.xhtml";
	}

	public List<Categoria> getCategorias() {
		if (this.categorias == null) {
			this.categorias = this.gerenciador.obterTodos();
		}

		return this.categorias;
	}

	public String prepararEdicao(Categoria aEditar) {
		if (this.conversation.isTransient()) {
			this.conversation.begin();
		}
		this.categoria = aEditar;

		return "cat_admin_editar?faces-redirect=true";
	}

	public String editarCategoria() {
		this.gerenciador.alterar(this.categoria);
		this.conversation.end();

		return "cat_admin_listar.xhtml";
	}

}

iDezBookWeb/src/main/java/com/davlopes/bookstore/LivroBean.java
package main.java.com.davlopes.bookstore;

import java.io.Serializable;
import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.davlopes.bookstore.manager.GerenciadorDeLivros;
import com.davlopes.bookstore.models.Categoria;
import com.davlopes.bookstore.models.Livro;


@Named
@ConversationScoped
public class LivroBean implements Serializable{

	private static final long serialVersionUID = 1L;

	private Livro livro;
	
	@EJB
	private GerenciadorDeLivros gerenciador;
	
	private List<Livro> livros;
	private List<Livro> lancamentos;

	@Inject
	private Conversation conversation;
	
	public LivroBean(){
		this.livro = new Livro();
		this.livro.setCategorias(new Categoria());
	}
	
	public Livro getLivro(){
		return this.livro;
	}	
	
	public void setLivro(Livro Livro){
		this.livro = Livro;
	}
	
	public String cadastrar(){
		this.gerenciador.cadastrar(this.livro);
		
		return "liv_admin_listar.xhtml";
	}
	
	public String remover(Livro l){
		this.gerenciador.remover(l);
		
		return "liv_admin_listar.xhtml";
	}
	
	public List<Livro> getLivros(){
		if(this.livros == null){
			this.livros = this.gerenciador.obterTodos();
		}
		
		return this.livros;
	}

	public List<Livro> getLancamentos() {
		if(this.lancamentos == null){
			this.lancamentos = this.gerenciador.obterLancamentos();
		}
		
		return this.lancamentos;
	}
	
	public String prepararEdicao(Livro aEditar) {
		if (this.conversation.isTransient()) {
			this.conversation.begin();
		}
		this.livro = aEditar;

		return "liv_admin_editar?faces-redirect=true";
	}
	
	public String editarLivro() {
		this.gerenciador.alterar(this.livro);
		this.conversation.end();

		return "liv_admin_listar.xhtml";
	}
	
	public void comprar(){
		System.out.println(this.livro);
	}
		
}

iDezBookWeb/src/main/java/com/davlopes/bookstore/LoginBean.java
package main.java.com.davlopes.bookstore;

import java.io.Serializable;

import javax.ejb.EJB;
import javax.enterprise.context.ConversationScoped;
import javax.inject.Named;

import com.davlopes.bookstore.manager.GerenciadorDeUsuarios;
import com.davlopes.bookstore.models.Usuario;

@Named
@ConversationScoped
public class LoginBean implements Serializable {

	private static final long serialVersionUID = 4348022157631061555L;

	@EJB
	private GerenciadorDeUsuarios gerenciador;
	
	private String nome;
	private String senha;
	
	public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	
	public String getSenha() {
		return senha;
	}
	public void setSenha(String senha) {
		this.senha = senha;
	}
	
	public String logar() {
		for(Usuario u : gerenciador.obterTodos()) {
			if (u.getNome().equals(this.nome) &&
					u.getSenha().equals(this.senha)) {
				return "admin.xhtml";
			}
		}
		return "invalido.xhtml";
	}
	
	public boolean getExisteUsusarios() {
		return !gerenciador.obterTodos().isEmpty();
	}
	
	
}

iDezBookWeb/src/main/java/com/davlopes/bookstore/UsuarioBean.java
package main.java.com.davlopes.bookstore;

import java.io.Serializable;
import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.davlopes.bookstore.manager.GerenciadorDeUsuarios;
import com.davlopes.bookstore.models.Usuario;


@Named
@ConversationScoped
public class UsuarioBean implements Serializable{

	private static final long serialVersionUID = 1L;

	private Usuario usuario;
	
	@Inject
	private Conversation conversation;
	
	@EJB
	private GerenciadorDeUsuarios gerenciador;
	
	private List<Usuario> usuarios;
	
	public UsuarioBean(){
		this.usuario = new Usuario();
	}
	
	public Usuario getUsuario(){
		return this.usuario;
	}	
	
	public void setUsuario(Usuario Usuario){
		this.usuario = Usuario;
	}
	
	public String cadastrar(){
		this.gerenciador.cadastrar(this.usuario);
		
		return "usu_admin_listar.xhtml";
	}
	
	public String remover(Usuario u){
		this.gerenciador.remover(u);
		
		return "usu_admin_listar.xhtml";
	}
	
	public List<Usuario> getUsuarios(){
		if(this.usuarios == null){
			this.usuarios = this.gerenciador.obterTodos();
		}
		
		return this.usuarios;
	}
	
	public String prepararEdicao(Usuario aEditar) {
		if (this.conversation.isTransient()) {
			this.conversation.begin();
		}
		this.usuario = aEditar;

		return "usu_admin_editar?faces-redirect=true";
	}
	
	public String editarUsuario() {
		this.gerenciador.alterar(this.usuario);
		this.conversation.end();

		return "usu_admin_listar.xhtml";
	}
	
}

iDezBookWeb/src/main/webapp/admin.xhtml
<?xml version="1.0" encoding="ISO-8859-1"?>
<ui:composition template="template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">

	<ui:define name="conteudo">
		<div class="container-narrow">
			<div class="masthead">
				<div class="row-fluid">
					<div class="span4">
						<h:form>
							<h:commandLink action="index.xhtml">
								<h3 class="muted">iDEZ BookStore</h3>
							</h:commandLink>
						</h:form>
					</div>
					<div class="span8 top"></div>
				</div>
			</div>
			<hr></hr>
			<div class="row-fluid">
				<div class="span4 well">
					<ul class="nav nav-list">
						<li class="nav-header">Categorias</li>
						<li><a href="cat_admin_cadastrar.xhtml">Cadastrar</a></li>
						<li><a href="cat_admin_listar.xhtml">Listar</a></li>
						<li class="divider"></li>
						<li class="nav-header">Livros</li>
						<li><a href="liv_admin_cadastrar.xhtml">Cadastrar</a></li>
						<li><a href="liv_admin_listar.xhtml">Listar</a></li>
						<li class="divider"></li>
						<li class="nav-header">Usuarios</li>
						<li><a href="usu_admin_cadastrar.xhtml">Cadastrar</a></li>
						<li><a href="usu_admin_listar.xhtml">Listar</a></li>
						<li class="divider"></li>
					</ul>
				</div>
				<div class="span8"></div>
			</div>
			<hr></hr>
			<div class="footer">
				<p>iDez BookStore 2013</p>
			</div>
		</div>
	</ui:define>
</ui:composition>

iDezBookWeb/src/main/webapp/cat_admin_cadastrar.xhtml
<?xml version="1.0" encoding="ISO-8859-1"?>
<ui:composition template="template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">

	<ui:define name="conteudo">
		<div class="container-narrow">
			<div class="masthead">
				<div class="row-fluid">
					<div class="span4">
						<h:form>
							<h:commandLink action="index.xhtml">
								<h3 class="muted">iDEZ BookStore</h3>
							</h:commandLink>
						</h:form>
					</div>
					<div class="span8 top"></div>
				</div>
			</div>
			<hr></hr>
			<div class="row-fluid">
				<div class="span4 well">
					<ul class="nav nav-list">
						<li class="nav-header">Categorias</li>
						<li><a href="cat_admin_cadastrar.xhtml">Cadastrar</a></li>
						<li><a href="cat_admin_listar.xhtml">Listar</a></li>
						<li class="divider"></li>
						<li class="nav-header">Livros</li>
						<li><a href="liv_admin_cadastrar.xhtml">Cadastrar</a></li>
						<li><a href="liv_admin_listar.xhtml">Listar</a></li>
						<li class="divider"></li>
						<li class="nav-header">Usuarios</li>
						<li><a href="usu_admin_cadastrar.xhtml">Cadastrar</a></li>
						<li><a href="usu_admin_listar.xhtml">Listar</a></li>
						<li class="divider"></li>
					</ul>
				</div>
				<div class="span8">
					<!--Form de categoria-->
					<legend>Cadastro de categoria:</legend>
					<h:form>
						<div class="control-group">
							<label class="control-label" for="inputNome">Nome:</label>
							<div class="controls">
								<h:inputText required="true" id="inputNome" value="#{categoriaBean.categoria.nome}" placeholder="Nome..." />
								<h:message for="inputNome" />
							</div>
							<h:commandButton value="Cadastrar"
								action="#{categoriaBean.cadastrar}" class="btn btn-primary" />
							<!-- <button type="reset" class="btn">Limpar</button> -->
						</div>
					</h:form>
				</div>
			</div>
			<hr></hr>
			<div class="footer">
				<p>iDez BookStore 2013</p>
			</div>
		</div>
	</ui:define>
</ui:composition>

iDezBookWeb/src/main/webapp/cat_admin_editar.xhtml
<?xml version="1.0" encoding="ISO-8859-1"?>
<ui:composition template="template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">

	<ui:define name="conteudo">
		<div class="container-narrow">
			<div class="masthead">
				<div class="row-fluid">
					<div class="span4">
						<h:form>
							<h:commandLink action="index.xhtml">
								<h3 class="muted">iDEZ BookStore</h3>
							</h:commandLink>
						</h:form>
					</div>
					<div class="span8 top"></div>
				</div>
			</div>
			<hr></hr>
			<div class="row-fluid">
				<div class="span4 well">
					<ul class="nav nav-list">
						<li class="nav-header">Categorias</li>
						<li><a href="cat_admin_cadastrar.xhtml">Cadastrar</a></li>
						<li><a href="cat_admin_listar.xhtml">Listar</a></li>
						<li class="divider"></li>
						<li class="nav-header">Livros</li>
						<li><a href="liv_admin_cadastrar.xhtml">Cadastrar</a></li>
						<li><a href="liv_admin_listar.xhtml">Listar</a></li>
						<li class="divider"></li>
						<li class="nav-header">Usuarios</li>
						<li><a href="usu_admin_cadastrar.xhtml">Cadastrar</a></li>
						<li><a href="usu_admin_listar.xhtml">Listar</a></li>
						<li class="divider"></li>
					</ul>
				</div>
				<div class="span8">
					<!--Form de categoria-->
					<legend>Editar Categoria:</legend>
					<h:form>
						<div class="control-group">
							<label class="control-label" for="inputNome">Nome:</label>
							<div class="controls">
								<h:inputText required="true" id="inputNome" value="#{categoriaBean.categoria.nome}" placeholder="Nome..." />
								<h:message for="inputNome" />
							</div>
							<h:commandButton value="Cadastrar"
								action="#{categoriaBean.editarCategoria}" class="btn btn-primary" />
							<!-- <button type="reset" class="btn">Limpar</button> -->
						</div>
					</h:form>
				</div>
			</div>
			<hr></hr>
			<div class="footer">
				<p>iDez BookStore 2013</p>
			</div>
		</div>
	</ui:define>
</ui:composition>

iDezBookWeb/src/main/webapp/cat_admin_listar.xhtml
<?xml version="1.0" encoding="ISO-8859-1"?>
<ui:composition template="template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">

	<ui:define name="conteudo">
		<div class="container-narrow">
			<div class="masthead">
				<div class="row-fluid">
					<div class="span4">
						<h:form>
							<h:commandLink action="index.xhtml">
								<h3 class="muted">iDEZ BookStore</h3>
							</h:commandLink>
						</h:form>
					</div>
					<div class="span8 top"></div>
				</div>
			</div>
			<hr></hr>
			<div class="row-fluid">
				<div class="span4 well">
					<ul class="nav nav-list">
						<li class="nav-header">Categorias</li>
						<li><a href="cat_admin_cadastrar.xhtml">Cadastrar</a></li>
						<li><a href="cat_admin_listar.xhtml">Listar</a></li>
						<li class="divider"></li>
						<li class="nav-header">Livros</li>
						<li><a href="liv_admin_cadastrar.xhtml">Cadastrar</a></li>
						<li><a href="liv_admin_listar.xhtml">Listar</a></li>
						<li class="divider"></li>
						<li class="nav-header">Usuarios</li>
						<li><a href="usu_admin_cadastrar.xhtml">Cadastrar</a></li>
						<li><a href="usu_admin_listar.xhtml">Listar</a></li>
						<li class="divider"></li>
					</ul>
				</div>
				<div class="span8">
					<legend>Listar categoria:</legend>
					<h:form>
					<h:dataTable class="table table-striped" value="#{categoriaBean.categorias}" var="c">
						<h:column>
							<f:facet name="header">
								<h:outputText value="Nome" />
							</f:facet>
							<h:outputText value="#{c.nome}" />
						</h:column>
						<h:column>
							<f:facet name="header">
								<h:outputText value="Acoes" />
							</f:facet>

							<h:commandButton value="Remover" actionListener="#{categoriaBean.remover(c)}" />
							<h:commandButton value="Editar"	actionListener="#{categoriaBean.prepararEdicao(c)}" />

						</h:column>
					</h:dataTable>
					</h:form>
				</div>
			</div>
			<hr></hr>
			<div class="footer">
				<p>iDez BookStore 2013</p>
			</div>
		</div>
	</ui:define>
</ui:composition>

iDezBookWeb/src/main/webapp/index.xhtml
<?xml version="1.0" encoding="ISO-8859-1"?>
<ui:composition template="/template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">

	<ui:define name="conteudo">

		<div class="jumbotron">
			<h1>iDEZ Bookstore Livraria Online</h1>
			<p class="lead">Bem vindo a iDEZBookstore!</p>
		</div>

		<center>	
			<h:form>
				<h:panelGrid columns="2" class="jumbotron" rendered="#{loginBean.existeUsusarios}">
						<h:outputText value="Nome: "/>
						<h:inputText value="#{loginBean.nome}" class="input-xlarge" placeholder="ISBN" />
						<h:outputText value="Senha: "/>
						<h:inputSecret value="#{loginBean.senha}" class="input-xlarge" placeholder="ISBN" />
						<h:column> </h:column>
						<h:commandButton value="Login" action="#{loginBean.logar}" class="btn btn-primary" />
				</h:panelGrid>
			</h:form>
		</center>
	
		<h:panelGroup class="jumbotron" rendered="#{!loginBean.existeUsusarios}">
			<center>
				<a class="btn btn-large btn-success" href="admin.xhtml">Entrar</a>
			</center>
		</h:panelGroup>

		<hr />

		<h:panelGroup class="row-fluid marketing" rendered="#{!loginBean.existeUsusarios}">
			<div class="span12">
				<h4>Ofertas</h4>
				<p>Aproveite, na compra de 2 livros, ganhe um gratis.</p>

				<h4>Novidades</h4>
				<p>
					<h:dataTable class="table table-striped"
						value="#{livroBean.lancamentos}" var="l">
						<h:column>
							<f:facet name="header">
								<h:outputText value="Titulo" />
							</f:facet>
							<h:outputText value="#{l.titulo}" />													
						</h:column>
						<h:column>
							<f:facet name="header">
								<h:outputText value="Autor" />
							</f:facet>
							<h:outputText value="#{l.autor}" />
						</h:column>
						<h:column>
							<f:facet name="header">
								<h:outputText value="Editora" />
							</f:facet>
							<h:outputText value="#{l.editora}" />
						</h:column>
						<h:column>
							<f:facet name="header">
								<h:outputText value="Valor" />
							</f:facet>
							<h:outputText value="#{l.preco}" />
						</h:column>
						<h:column>
							<f:facet name="header">
								<h:outputText value="" />
							</f:facet>

							<h:commandButton value="Comprar" actionListener="#{livroBean.comprar(c)}" />
						</h:column>
					</h:dataTable>
				</p>

				<h4>Mais comprados</h4>
				<p>Funcionalidade em desenvolvimento.</p>
			</div>
		</h:panelGroup>

		<hr />
	</ui:define>
</ui:composition>

iDezBookWeb/src/main/webapp/invalido.xhtml
<?xml version="1.0" encoding="ISO-8859-1"?>
<ui:composition template="/template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">

	<ui:define name="conteudo">
		<div class="jumbotron">
			<h1>iDEZ Bookstore Livraria Online</h1>
			<p class="lead">Login invalido.</p>
			<a class="btn btn-large btn-success" href="index.xhtml">Voltar para tela de login</a>
		</div>
	</ui:define>
</ui:composition>

iDezBookWeb/src/main/webapp/liv_admin_listar.xhtml
<?xml version="1.0" encoding="ISO-8859-1"?>
<ui:composition template="template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">

	<ui:define name="conteudo">
		<div class="container-narrow">
			<div class="masthead">
				<div class="row-fluid">
					<div class="span4">
						<h:form>
							<h:commandLink action="index.xhtml">
								<h3 class="muted">iDEZ BookStore</h3>
							</h:commandLink>
						</h:form>
					</div>
					<div class="span8 top"></div>
				</div>
			</div>
			<hr></hr>
			<div class="row-fluid">
				<div class="span4 well">
					<ul class="nav nav-list">
						<li class="nav-header">Categorias</li>
						<li><a href="cat_admin_cadastrar.xhtml">Cadastrar</a></li>
						<li><a href="cat_admin_listar.xhtml">Listar</a></li>
						<li class="divider"></li>
						<li class="nav-header">Livros</li>
						<li><a href="liv_admin_cadastrar.xhtml">Cadastrar</a></li>
						<li><a href="liv_admin_listar.xhtml">Listar</a></li>
						<li class="divider"></li>
						<li class="nav-header">Usuarios</li>
						<li><a href="usu_admin_cadastrar.xhtml">Cadastrar</a></li>
						<li><a href="usu_admin_listar.xhtml">Listar</a></li>
						<li class="divider"></li>
					</ul>
				</div>
				<div class="span8">
					<h:form>
					<h:dataTable class="table table-striped"
						value="#{livroBean.livros}" var="l">
						<h:column>
							<f:facet name="header">
								<h:outputText value="Titulo" />
							</f:facet>
							<h:outputText value="#{l.titulo}" />
						</h:column>
						<h:column>
							<f:facet name="header">
								<h:outputText value="Autor" />								
							</f:facet>
							<h:outputText value="#{l.autor}" />
						</h:column>
						<h:column>
							<f:facet name="header">
								<h:outputText value="Editora" />								
							</f:facet>
							<h:outputText value="#{l.editora}" />
						</h:column>
						<h:column>
							<f:facet name="header">
								<h:outputText value="Valor" />								
							</f:facet>
							<h:outputText value="#{l.preco}" />
						</h:column>
						<h:column>
							<f:facet name="header">
								<h:outputText value="Estoque" />								
							</f:facet>
							<h:outputText value="#{l.qnt_estoque}" />
						</h:column>
						<h:column>
							<f:facet name="header">
								<h:outputText value="Acoes" />
							</f:facet>

							<h:commandButton value="Remover" actionListener="#{livroBean.remover(l)}" />
							<h:commandButton value="Editar"	actionListener="#{livroBean.prepararEdicao(l)}" />

						</h:column>
					</h:dataTable>
					</h:form>
				</div>
			</div>
			<hr></hr>
			<div class="footer">
				<p>iDez BookStore 2013</p>
			</div>
		</div>
	</ui:define>
</ui:composition>

iDezBookWeb/src/main/webapp/template.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	<meta charset="utf-8" />
	<title>iDEZ BookStore</title>	
	
	<!-- Le styles -->
	<link href="arquivos/bootstrap.css" rel="stylesheet" />        
	<link href="arquivos/bootstrap-responsive.css" rel="stylesheet" />
	<link href="arquivos/style.css" rel="stylesheet" />        
	
	<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	
	<!-- Fav and touch icons -->
	<link rel="shortcut icon" href="http://twitter.github.com/bootstrap/assets/ico/favicon.ico" />
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-144-precomposed.png" />
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-114-precomposed.png" />
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-72-precomposed.png" />
	<link rel="apple-touch-icon-precomposed" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-57-precomposed.png" />
</head>

<body>


	<ui:insert name="conteudo">
	a ser alterado!!!  
  </ui:insert>

</body>

</html>

iDezBookWeb/src/main/webapp/usu_admin_listar.xhtml
<?xml version="1.0" encoding="ISO-8859-1"?>
<ui:composition template="template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">

	<ui:define name="conteudo">
		<div class="container-narrow">
			<div class="masthead">
				<div class="row-fluid">
					<div class="span4">
						<h:form>
							<h:commandLink action="index.xhtml">
								<h3 class="muted">iDEZ BookStore</h3>
							</h:commandLink>
						</h:form>
					</div>
					<div class="span8 top"></div>
				</div>
			</div>
			<hr></hr>
			<div class="row-fluid">
				<div class="span4 well">
					<ul class="nav nav-list">
						<li class="nav-header">Categorias</li>
						<li><a href="cat_admin_cadastrar.xhtml">Cadastrar</a></li>
						<li><a href="cat_admin_listar.xhtml">Listar</a></li>
						<li class="divider"></li>
						<li class="nav-header">Livros</li>
						<li><a href="liv_admin_cadastrar.xhtml">Cadastrar</a></li>
						<li><a href="liv_admin_listar.xhtml">Listar</a></li>
						<li class="divider"></li>
						<li class="nav-header">Usuarios</li>
						<li><a href="usu_admin_cadastrar.xhtml">Cadastrar</a></li>
						<li><a href="usu_admin_listar.xhtml">Listar</a></li>
						<li class="divider"></li>
					</ul>
				</div>
				<div class="span8">
					<h:form>
						<h:dataTable class="table table-striped"
							value="#{usuarioBean.usuarios}" var="u">
							<h:column>
								<f:facet name="header">
									<h:outputText value="Nome" />
								</f:facet>
								<h:outputText value="#{u.nome}" />
							</h:column>
							<h:column>
								<f:facet name="header">
									<h:outputText value="Rua" />
								</f:facet>
								<h:outputText value="#{u.endereco.rua}" />
							</h:column>
							<h:column>
								<f:facet name="header">
									<h:outputText value="Bairro" />
								</f:facet>
								<h:outputText value="#{u.endereco.bairro}" />
							</h:column>
							<h:column>
								<f:facet name="header">
									<h:outputText value="Numero" />
								</f:facet>
								<h:outputText value="#{u.endereco.numero}" />
							</h:column>
							<h:column>
								<f:facet name="header">
									<h:outputText value="Data Nascimento" />
								</f:facet>
								<h:outputText value="#{u.data_nasc}" />
							</h:column>
							<h:column>
								<f:facet name="header">
									<h:outputText value="Email" />
								</f:facet>
								<h:outputText value="#{u.email}" />
							</h:column>
							<h:column>
								<f:facet name="header">
									<h:outputText value="Acoes" />
								</f:facet>

								<h:commandButton value="Remover"
									action="#{UsuarioBean.remover(u)}" />
								<h:commandButton value="Editar"
									action="#{UsuarioBean.prepararEdicao(u)}" />

							</h:column>
						</h:dataTable>
					</h:form>
				</div>
			</div>
			<hr></hr>
			<div class="footer">
				<p>iDez BookStore 2013</p>
			</div>
		</div>
	</ui:define>
</ui:composition>